execute:
  fields:
    entity_id:
      required: true
      selector:
        entity: {}
    action:
      required: true
      selector:
        select:
          options:
            - turn_on
            - turn_off
            - toggle
            - open_cover
            - close_cover
            - stop_cover
            - media_play
            - media_pause
            - media_stop
            - media_next_track
            - media_previous_track
            - volume_mute
            - volume_up
            - volume_down
            - lock
            - unlock
            - start
            - stop
            - return_to_base
            - dock
            - start_mowing
            - select_option
            - trigger
    delay:
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds
    datetime:
      selector:
        datetime: {}
    data:
      selector:
        object: {}

cancel:
  fields:
    entity_id:
      required: true
      selector:
        entity: {}
    task_id:
      selector:
        text: {}

list:
  fields:
    entity_id:
      selector:
        entity: {}

get_config:
  fields: {}
